---
AllowedHosts: "*"
UseInMemoryDatabase: false

SwaggerSettings:
  Name: CleanDDD API
  RoutePrefix: docs
  DefaultApiVersion:
    Major: 1
    Minor: 0
  Info:
    Title: Current API
    Description: Clean DDD Architecture Demo Project API
    TermsOfService: https://company.com/termsofservice
    Contact:
      Name: John Doe
      Email: j.doe@email.com
      Url: https://support.company.com/helpdesk
    License:
      Name: MIT
      Url: https://opensource.org/licenses/MIT
  VersionInfo:
    V1_1:
      Title: Beta API
      Contact:
        Name: New Guy
        Email: new.guy@email.com
        Url: https://support.company.com/helpdesk-v1-1

FeatureManagement:
  Metal: true
  
# Use secrets.json for these:
#  {
#    // RestAPI Release
#    "ConnectionStrings": {
#      "MSSQLConnection": "Server=CleanDDDArchitecture-mssql,1433;Database=CleanDDDArchitecture;User Id=sa;Password=XpU7oFh3HRFoG6;MultipleActiveResultSets=true;TrustServerCertificate=true;",
#      "PGSQLConnection": "Server=CleanDDDArchitecture-postgres;Port=5432;Database=CleanDDDArchitecture;User ID =panosru;Password=rX3t9bvDT2ftH2;Pooling=true;",
#      "Hangfire": "Server=CleanDDDArchitecture-mssql,11433;Database=Hangfire;User Id=sa;Password=XpU7oFh3HRFoG6;MultipleActiveResultSets=true;TrustServerCertificate=true;",
#      "eventstore": "tcp://admin:changeit@CleanDDDArchitecture-eventstore:1113",
#      "kafka": "CleanDDDArchitecture-kafka:9092",
#      "loki": "http://CleanDDDArchitecture-loki:3100",
#      "mongo": "mongodb://CleanDDDArchitecture-mongo:27017"
#    },
#    
#    "Jwt": {
#      "Access": {
#        "Key512Bit": "Nioi18q5M4dQKM92Pho2WwXBIis3f257Ped4J4m2gpIRaoS0jZBMY8Kp0EvNuQsa",
#        "Key256Bit": "yulEJ2CRbyvzTbyorcZoiznSlfZ4SE5T",
#      },
#      "Refresh": {
#        "Key512Bit": "RL3tJAjSjS55nGp0ZxjdhqQxPWjKIogldPEQr0xPJHE6le5FoEC4Y2N2bjRVaA0n",
#        "Key256Bit": "rnLzkCWxRVdNPTxUIAuw5q8LPGOACJ6Z"
#      }
#    }
#  }
